language: python

os: linux

python: 3.6

before_install:
  - python --version
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update;
    brew install python3.6;
    pip3 install codecov;
    pip3 install --user -r requirements.txt;
    fi

install: 
  - pip install pylint


script:
  - pylint *.py
  - python helloworldtest.py