language: python

os: linux

python: 3.6

before_install:
  - python --version

install: 
  - pip install pylint
  - pip install codecov
  - pip install matplotlib

script:
  - pylint *.py
  - coverage run -a test_filterbank.py 
  - coverage run -a test_header.py

after_success:
  - codecov
