language: python

os: linux

python: 3.6

before_install:
  - python --version

install: 
  - pip install pylint
  - pip install codecov
  - pip install matplotlib

script:
  - pylint *.py
  - coverage run readertest.py

after_success:
  - codecov
