language: python

os:
    - linux
    - osx

python: 3.6

before_install:
  - python --version
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update;
    brew install python3
    fi

install: 
  - pip install pylint


script:
  - pylint *.py
  - python helloworldtest.py