matrix:
  include:
    - os: linux
      language: python
      python: 3.6
      
    - os: osx
      language: generic

before_install:
  - python --version

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew upgrade python;
    fi

install: 
  - pip install pylint

script:
  - pylint *.py
  - python helloworldtest.py