language: python

os:
    - linux
    - osx

python: 3.6

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
- python --version

install: 
  - pip install pylint


script:
  - pylint *.py
  - python helloworldtest.py